language: csharp
solution: api.syski.co.uk.sln
mono: none
dotnet: 2.1.504
os: 
 - linux
 - windows
install:
 - dotnet restore "csharp/csharp.csproj"
script:
 - dotnet build "csharp/csharp.csproj" -c Release -o /app